Location: 'northeurope'

ResourceGroups:
  - Name: rg-personalsite
    Location: 'northeurope'

VirtualNetwork:
  Name: vnet-personalsite
  ResourceGroupName: rg-personalsite
  AddressSpaces:
    - 10.1.0.0/16
  Subnets:
    - Name: subnet-aks
      SubnetAddress: 10.1.2.0/24
      NetworkSecurityGroup: nsg-aks
      RouteTable: rt-aks
    - Name: subnet-db
      SubnetAddress: 10.1.3.0/24
      NetworkSecurityGroup: nsg-db
      RouteTable: rt-db
  Location: 'northeurope'

NetworkSecurityGroups:
  - Name: nsg-aks
    ResourceGroupName: rg-personalsite
    Rules:
      - Name: Allow-HTTP
        Priority: 100
        Direction: Inbound
        Access: Allow
        Protocol: Tcp
        SourcePortRange: "*"
        DestinationPortRange: "80"
        SourceAddressPrefix: "*"
        DestinationAddressPrefix: "*"
      - Name: Allow-HTTPS
        Priority: 110
        Direction: Inbound
        Access: Allow
        Protocol: Tcp
        SourcePortRange: "*"
        DestinationPortRange: "443"
        SourceAddressPrefix: "*"
        DestinationAddressPrefix: "*"
  - Name: nsg-db
    ResourceGroupName: rg-personalsite
    Rules:
      - Name: Allow-DB
        Priority: 100
        Direction: Inbound
        Access: Allow
        Protocol: Tcp
        SourcePortRange: "*"
        DestinationPortRange: "5432"
        SourceAddressPrefix: "*"
        DestinationAddressPrefix: "*"

RouteTables:
  - Name: rt-aks
    ResourceGroupName: rg-personalsite
    Routes:
      - Name: default-route
        AddressPrefix: "0.0.0.0/0"
        NextHopType: "Internet"
  - Name: rt-db
    ResourceGroupName: rg-personalsite
    Routes:
      - Name: default-route
        AddressPrefix: "0.0.0.0/0"
        NextHopType: "Internet"

AzureKubernetesCluster:
  Name: cluster-personalsite
  ResourceGroupName: rg-personalsite
  Location: 'northeurope'
  NodeCount: 1
  NodeSize: "Standard_B2s"
  DnsPrefix: 'personalsite'
  SubnetName: 'subnet-aks'
  NetworkProfile:
    NetworkPlugin: 'kubenet'
    LoadBalancerSku: 'basic'
    OutboundType: 'loadBalancer'

ContainerRegistry:
  Name: acrpersonalsite
  ResourceGroupName: rg-personalsite
  Location: 'northeurope'
  Sku: 'Basic'  # Cost-effective SKU for development
  AdminEnabled: false  # Disable if admin access is not required

StorageAccount:
  Name: markpersonalsite
  ResourceGroupName: rg-personalsite
  Location: 'northeurope'
  AccountTier: 'Standard'
  AccountReplicationType: 'LRS'
  
StorageContainer:
  - Name: tfstate
    ContainerAccessType: 'private'

UserAssignedIdentity:
  Name: personalsite-identity
  ResourceGroupName: rg-personalsite
  Location: 'northeurope'
