service:
  name: personalsite
  type: ClusterIP
  port: 80
  targetPort: 8080

selector:
  app: personalsite

replicaCount: 2

image:
  repository: acrmark.azurecr.io/personalsite
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""  # If left empty, the default name will be used
  automount: true

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "http01-cluster-issuer"
  hosts:
    - host: markmikula.software
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - markmikula.software
      secretName: markmikula.software-tls

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources: {}
livenessProbe: {}
readinessProbe: {}
securityContext: {}
podSecurityContext: {}
volumeMounts: []
volumes: []
nodeSelector: {}
affinity: {}
tolerations: []
imagePullSecrets:
  - name: acr-secret