fullnameOverride: ""
service:
  name: personalsite
  type: ClusterIP
  ports:
    web:
      servicePort: 80
      containerPort: 8080
    turing:
      servicePort: 5002
      containerPort: 5002
    prisoner:
      servicePort: 5000
      containerPort: 5000

selector:
  app: personalsite

replicaCount: 2

images:
  web:
    repository: acrpersonalsite.azurecr.io/web
    tag: latest
    pullPolicy: IfNotPresent
    env:
      TURING_SERVICE_URL: "http://localhost:5002"
      PRISONER_SERVICE_URL: "http://localhost:5000"
  turingService:
    repository: acrpersonalsite.azurecr.io/turing-service
    tag: latest
    pullPolicy: IfNotPresent
  prisonerService:
    repository: acrpersonalsite.azurecr.io/prisoner-service
    tag: latest
    pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""  # If left empty, the default name will be used
  automount: true

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "http01-mark-cluster-issuer"
  hosts:
    - host: markmikula.software
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - markmikula.software
      secretName: markmikula.software-tls

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources: {}
livenessProbe: {}
readinessProbe: {}
securityContext: {}
podSecurityContext: {}
volumeMounts: []
volumes: []
nodeSelector: {}
affinity: {}
tolerations: []
imagePullSecrets:
  - name: acr-secret
