apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: personal-website-repo
  namespace: mark
spec:
  interval: 1m
  url:  https://github.com/Humancannonball/DevOps-project
  ref:
    branch: master
  secretRef:
    name: flux-git-token