apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-issuer
  namespace: flux-system
spec:
  interval: 2m0s
  path: "./cluster-issuer.yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager   # This Kustomization must have this name