apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: web
        image: {{ .Values.images.web.repository }}:{{ .Values.images.web.tag }}
        imagePullPolicy: {{ .Values.images.web.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.ports.web.containerPort }}
        env:
        {{- range $key, $value := .Values.images.web.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
      - name: turing
        image: {{ .Values.images.turingService.repository }}:{{ .Values.images.turingService.tag }}
        imagePullPolicy: {{ .Values.images.turingService.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.ports.turing.containerPort }}
      - name: prisoner
        image: {{ .Values.images.prisonerService.repository }}:{{ .Values.images.prisonerService.tag }}
        imagePullPolicy: {{ .Values.images.prisonerService.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.ports.prisoner.containerPort }}