name: Verify Secrets Info
on:
  workflow_dispatch:
jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        run: |
          az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: List Resource Groups
        run: az group list --query "[].{Name:name, Location:location}" --output table
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: List Virtual Networks
        run: az network vnet list --query "[].{Name:name, ResourceGroup:resourceGroup, Location:location, AddressSpace:addressSpace}" --output table
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: List Storage Accounts
        run: az storage account list --query "[].{Name:name, ResourceGroup:resourceGroup, Location:location, Sku:sku.name}" --output table
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}